import networkx as nx
import matplotlib.pyplot as plt
import sys
import argparse

parser = argparse.ArgumentParser(description='Graph Parser')
parser.add_argument("--input", type=str, help="Graph input file")
parser.add_argument("--create_random_graph", nargs="+", type=int, help="Create a random graph with n nodes generated by a constant c")
parser.add_argument("--BFS", type=int, help="Specifies a node to compute all shortest paths from using the BFS algorithm")
args = parser.parse_args()

def main():
    print(args.input)

if __name__ == "__main__":
    main()

# Create a graph
#G = nx.Graph()

# Add nodes and edges
#G.add_nodes_from([1, 2, 3])
#G.add_edges_from([(1, 2), (2, 3)])

# Draw the graph
#nx.draw(G, with_labels=True)
#plt.show()
